// icon_lib.js — S7.1: **داده‌ی** آیکون‌های UI روی رمپ (منبع واحد: art/ramps.js)
// هر آیکون = ماده + نگاشتِ کاراکتر→پله (۰ تیره … ۶ روشن) + گریدِ هنر (از icons.js دست‌نخورده کپی شد)
// پخت (نورِ بالا-چپ + outline جوهر) در icons.js است — این فایل فقط داده است تا زیرِ سقفِ ۲۸۰ خط بماند
// پله‌ها عمداً روشن (۴..۶): رَمپ تا L۹۲ می‌رود و پس‌زمینه‌ی UI تا L۴۳ ⇒ میانگینِ بدنه باید ≥۷۳ بماند (ΔL ≥ ۳۰)

export const ICONS = {
  coin: { ramp: 'gold',
    map: {y: 5, Y: 6, d: 2},
    mix: {o: ['ink', 7]},
    rows: [
      '................',
      '.....oooooo.....',
      '....oyyyyyyo....',
      '...oyyYYYYyyo...',
      '..oyYyyyyyyYyo..',
      '..oyYyyyyyyyYo..',
      '..oyYyyyydddYo..',
      '..oyYyyyydddYo..',
      '..oyYyyyydddYo..',
      '..oyYyyyyyyyYo..',
      '..oyYyyyyyyYyo..',
      '...oyyYYYYyyo...',
      '....oyyyyyyo....',
      '.....oooooo.....',
      '................',
      '................',
    ],
  },
  gem: { ramp: 'magicCyan',
    map: {C: 5, c: 4, W: 6},
    mix: {g: ['ink', 7]},
    rows: [
      '................',
      '.....gggggg.....',
      '....gWWCCWCg....',
      '...gWCCCCCCCg...',
      '..gWCCcCCCcCCg..',
      '..gWCCCCCCCCCg..',
      '..gWCCcCCCcCCg..',
      '...gWCCCCCCCg...',
      '...gWCCcCCCcg...',
      '....gWCCCCCg....',
      '....gWCCcCCg....',
      '.....gWCCCg.....',
      '.....gWCcCg.....',
      '......gWCg......',
      '.......gg.......',
      '................',
    ],
  },
  snd: { ramp: 'metal',
    map: {x: 5, W: 6},
    mix: {y: ['magicCyan', 5]},
    rows: [
      '................',
      '.......xx.......',
      '......xxx..y....',
      '.....Wxxx..yy...',
      '....WWxxx...yy..',
      '....WWxxx....yy.',
      '....WWxxx....yy.',
      '....WWxxx....yy.',
      '....WWxxx....yy.',
      '.....Wxxx...yy..',
      '......xxx..yy...',
      '.......xx..y....',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  sndOff: { ramp: 'metal',
    map: {x: 5, W: 6},
    mix: {r: ['clothRed', 5]},
    rows: [
      '................',
      '.......xx.......',
      '......xxx.......',
      '.....Wxxx.......',
      '....WWxxx.r..r..',
      '....WWxxx..rr...',
      '....WWxxx...r...',
      '....Wxxx...rr...',
      '....Wxxx..r..r..',
      '.....xxx........',
      '......xxx.......',
      '.......xx.......',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  gear: { ramp: 'metal',
    map: {y: 5, Y: 6, x: 4},
    rows: [
      '................',
      '...x...xx...x...',
      '...xx.xxxx.xx...',
      '....xxYYyyxx....',
      '..xxxYyyyyYxxx..',
      '..xxYyyyyyyyYx..',
      '..xYyyyyyyyyyYx.',
      '..xYyyyyyyyyyx..',
      '..xYyyyyyyyyyx..',
      '..xYyyyyyyyyyYx.',
      '..xxYyyyyyyyYx..',
      '..xxxYyyyyYxxx..',
      '....xxYYyyxx....',
      '...xx.xxxx.xx...',
      '...x...xx...x...',
      '................',
    ],
  },
  worker: { ramp: 'leaf',
    map: {b: 5, B: 3},
    mix: {h: ['gold', 5], H: ['gold', 4], s: ['skin', 6], e: ['ink', 7]},
    rows: [
      '................',
      '.....hhhhhh.....',
      '....hhhhhhhh....',
      '...hhhhhhhhhh...',
      '..hHhhhhhhhhHh..',
      '....ssssssss....',
      '....sesssses....',
      '....ssssssss....',
      '.....ssssss.....',
      '....bbbbbbbb....',
      '...BbbbbbbbbB...',
      '...sBbbbbbbBs...',
      '....BbbbbbbB....',
      '....BB....BB....',
      '....ss....ss....',
      '................',
    ],
  },
  drop: { ramp: 'water',
    map: {w: 5, d: 4, W: 6},
    rows: [
      '................',
      '.......W........',
      '.......WW.......',
      '......WWww......',
      '......Wwww......',
      '.....WwwwwW.....',
      '....WwwwwwwW....',
      '...WwwwwwwwwW...',
      '...WwWwwwwwww...',
      '...WwWwwwwwwd...',
      '...Wwwwwwwwdd...',
      '...Wwwwwwwwdd...',
      '....Wwwwwwdd....',
      '.....WWWWWW.....',
      '................',
      '................',
    ],
  },
  basket: { ramp: 'soil',
    map: {K: 6, k: 5, d: 4},
    rows: [
      '................',
      '......KKKK......',
      '.....K....K.....',
      '....K......K....',
      '...K........K...',
      '...kkkkkkkkkk...',
      '..kKkKkKkKkKkk..',
      '..kKkKkKkKkKkk..',
      '..kkkkkkkkkkkk..',
      '...kdkkdkkdkk...',
      '...kkkkkkkkkk...',
      '....dddddddd....',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  salad: { ramp: 'leaf',
    map: {g: 4, G: 6},
    mix: {o: ['fire', 5], w: ['bone', 6], r: ['clothRed', 5], s: ['clothRed', 4]},
    rows: [
      '............',
      '...G..g.G...',
      '..gG.Gg.gG..',
      '..o.Go.o.G..',
      '.wGgwGgwGgw.',
      '.wrrrrrrrrw.',
      '..wrrrrrrw..',
      '...swwwws...',
      '............',
    ],
  },
  bread: { ramp: 'sand',
    map: {b: 5, B: 6, d: 4, D: 4},
    rows: [
      '............',
      '...BBBBBB...',
      '..BBdBBdBB..',
      '.BdBBDdBBDb.',
      '.BbBbBbBbBb.',
      '.dddddddddd.',
      '............',
    ],
  },
  pie: { ramp: 'sand',
    map: {c: 5},
    mix: {o: ['fire', 4], O: ['fire', 5], w: ['bone', 6]},
    rows: [
      '............',
      '...cccccc...',
      '..cOOOOOOc..',
      '.cOwOOwOOwc.',
      '.cOOOOOOOOc.',
      '..cccccccc..',
      '............',
    ],
  },
  sword: { ramp: 'metal',
    map: {s: 5, S: 6},
    mix: {g: ['soil', 4], G: ['gold', 5]},
    rows: [
      '................',
      '..........Ss....',
      '.........Ss.....',
      '........Ss......',
      '.......Ss.......',
      '......Ss........',
      '.....Ss.........',
      '....Ss..........',
      '...Gg...........',
      '..GGgG..........',
      '.Gg..gG.........',
      '......g.........',
      '................',
      '................',
      '................',
      '................',
    ],
  },
};

// ماده/پله‌ی یک کاراکتر (mix بر map مقدم است)
export const ICON_KINDS = Object.keys(ICONS);
export const matOf = (art, ch) => (art.mix && art.mix[ch]) ? art.mix[ch][0] : art.ramp;
export const stepOf = (art, ch) => (art.mix && art.mix[ch]) ? art.mix[ch][1] : (art.map[ch] ?? 5);

