// floors/f001_010.js — طراحیِ دستیِ طبقه‌های ۱..۱۰ (فصلِ ۱ لجن، فصلِ ۲ خفاش). هر طبقه یک چیدمان و حالِ متفاوت.
// کلیدها (dungeon_gen): layout, cols/rows, rooms, rw/rh (بازه‌ی پهنا/بلندیِ اتاق), cw (پهنای راهرو), round (برشِ گوشه),
// cross (احتمالِ اتاقِ صلیبی), pillars/pools (احتمالِ ستون/حوض در اتاقِ بزرگ), loops (حلقه‌ی اضافه), winding (راهروی پیچان),
// treasure (اتاقِ گنج), empty (احتمالِ اتاقِ خالی), dens (تراکمِ گروه), startAt, boss
export const F001_010 = {
  1: { centre: ['well'], centreN: 2, shapes: ['rect','oval'], dress: ['puddle','moss'], name: { fa: 'ورودیِ نمور', en: 'Damp Entrance' }, layout: 'scatter', cols: 96, rows: 72, rooms: 10, rw: [12, 18], rh: [9, 13],
    round: 2, loops: 0.03, treasure: 1, empty: 0.35, dens: 0.7, startAt: 'left' },
  2: { centre: ['bones'], centreN: 2, dress: ['puddle','rubble'], name: { fa: 'راهروهای چکه', en: 'Dripping Passages' }, layout: 'chain', cols: 96, rows: 72, rooms: 12, chainCols: 4, rw: [12, 17], rh: [9, 12],
    winding: true, treasure: 2, empty: 0.3, dens: 0.8, startAt: 'top' },
  3: { centre: ['statue'], centreN: 2, shapes: ['ring','rect'], dress: ['rubble'], banners: 0.4, name: { fa: 'تالارِ ستون‌ها', en: 'Hall of Pillars' }, layout: 'hub', cols: 112, rows: 84, rooms: 13, rw: [12, 18], rh: [9, 13],
    pillars: 0.8, round: 1, treasure: 2, empty: 0.25, dens: 0.9 },
  4: { centre: ['fountain'], centreN: 2, shapes: ['oval'], dress: ['puddle','moss'], dressN: 0.13, name: { fa: 'حوضچه‌های لجن', en: 'Ooze Pools' }, layout: 'scatter', cols: 112, rows: 84, rooms: 15, rw: [13, 20], rh: [10, 14],
    pools: 0.7, loops: 0.12, round: 3, treasure: 2, empty: 0.25, dens: 1 },
  5: { centre: ['altar', 'bones'], centreN: 2, shapes: ['oval','rect'], dress: ['puddle','bones'], banners: 0.5, name: { fa: 'تختِ شاه‌لجن', en: 'Throne of the Slime King' }, layout: 'ring', cols: 112, rows: 84, rooms: 12, spokes: 3, rw: [12, 17], rh: [9, 12],
    round: 2, pools: 0.4, treasure: 2, empty: 0.2, dens: 1, boss: true },
  6: { centre: ['bones', 'cage'], centreN: 2, shapes: ['L','rect'], dress: ['bones','rubble'], name: { fa: 'دهانه‌ی دوقلو', en: 'Twin Mouths' }, layout: 'twin', cols: 112, rows: 84, rooms: 14, rw: [12, 18], rh: [9, 13],
    round: 3, loops: 0.08, treasure: 2, empty: 0.3, dens: 0.9, startAt: 'left' },
  7: { centre: ['statue', 'altar'], centreN: 2, shapes: ['ring','rect'], dress: ['rubble','bones'], banners: 0.4, name: { fa: 'سقف‌های بلند', en: 'High Vaults' }, layout: 'grid', cols: 112, rows: 84, gridCols: 5, gridRows: 4, holes: 0.15, rw: [12, 16], rh: [9, 12],
    pillars: 0.45, round: 1, treasure: 3, empty: 0.25, dens: 1 },
  8: { centre: ['bones'], centreN: 2, shapes: ['L','oval'], dress: ['bones','moss'], name: { fa: 'پیچ‌وتابِ تاریک', en: 'Dark Coils' }, layout: 'chain', cols: 120, rows: 90, rooms: 15, chainCols: 5, rw: [12, 17], rh: [9, 13],
    winding: true, cross: 0.4, treasure: 2, empty: 0.2, dens: 1.1, startAt: 'top' },
  9: { centre: ['well', 'fountain'], centreN: 2, shapes: ['oval','ring'], dress: ['puddle','moss'], dressN: 0.13, name: { fa: 'چاه‌های آب', en: 'Cistern Wells' }, layout: 'hub', cols: 120, rows: 90, rooms: 15, rw: [13, 19], rh: [10, 14],
    pools: 0.6, cross: 0.5, loops: 0.1, treasure: 2, empty: 0.2, dens: 1.1 },
  10: { centre: ['bones', 'altar'], centreN: 2, shapes: ['oval','L'], dress: ['bones','bones','rubble'], banners: 0.5, name: { fa: 'آشیانه‌ی مادر', en: 'The Matriarch Roost' }, layout: 'ring', cols: 120, rows: 90, rooms: 14, spokes: 4, rw: [12, 18], rh: [9, 13],
    round: 3, pillars: 0.35, treasure: 2, empty: 0.15, dens: 1.2, boss: true },
};
