// floors/f041_060.js — بازطراحیِ دستیِ طبقه‌های ۴۱..۶۰ (ن۱۴۴؛ جایگزینِ نسخه‌ی جدول‌محورِ ن۱۴۲).
// فصلِ ۹ کمانداران (دژ)، ۱۰ گرگ‌ها (جنگلِ زیرزمینی)، ۱۱ قوچ‌ها (تونل‌های شاخ)، ۱۲ یتی (یخچال). centre = قطعه‌ی مرکزیِ ۲×۲ (dungeon_paint.paintCentre).
export const F041_060 = {
  // — دژِ کمانداران: اتاق‌های مستطیلِ منظم، پرچمِ زیاد، تیرهای فرورفته، مجسمه و سندان —
  41: { name: { fa: 'برج‌های دیده‌بانی', en: 'Watchtowers' }, layout: 'grid', cols: 128, rows: 96, gridCols: 5, gridRows: 4, holes: 0.25, rw: [12, 15], rh: [10, 12],
    round: 1, shapes: ['rect'], dress: ['arrows', 'rubble'], dressN: 0.1, banners: 0.7, centre: ['statue'], centreN: 3, treasure: 2, empty: 0.25, dens: 1.55, startAt: 'left' },
  42: { name: { fa: 'باروی شکسته', en: 'Broken Ramparts' }, layout: 'chain', cols: 136, rows: 90, rooms: 16, chainCols: 6, rw: [13, 18], rh: [9, 11],
    winding: true, round: 2, shapes: ['rect', 'L'], dress: ['rubble', 'rubble', 'arrows'], dressN: 0.16, banners: 0.3, centre: ['bones'], centreN: 2, treasure: 2, empty: 0.2, dens: 1.57, startAt: 'top' },
  43: { name: { fa: 'اسلحه‌خانه', en: 'The Armory' }, layout: 'hub', cols: 136, rows: 96, rooms: 16, rw: [13, 18], rh: [10, 13],
    round: 1, pillars: 0.4, shapes: ['rect'], dress: ['armor', 'arrows'], dressN: 0.13, banners: 0.6, centre: ['anvil'], centreN: 4, treasure: 3, empty: 0.15, dens: 1.59 },
  44: { name: { fa: 'حیاطِ تمرین', en: 'Training Yard' }, layout: 'twin', cols: 136, rows: 96, rooms: 16, rw: [15, 21], rh: [11, 14],
    round: 2, shapes: ['ring', 'rect'], dress: ['arrows', 'arrows', 'sand'], dressN: 0.12, banners: 0.5, centre: ['statue', 'well'], centreN: 3, treasure: 2, empty: 0.3, dens: 1.60, startAt: 'left' },
  45: { name: { fa: 'تختِ فرمانده‌ی کمان', en: 'Bowmaster Throne' }, layout: 'ring', cols: 136, rows: 96, rooms: 14, spokes: 4, rw: [12, 17], rh: [10, 13],
    round: 1, shapes: ['rect', 'ring'], dress: ['arrows', 'armor'], dressN: 0.14, banners: 0.9, centre: ['statue'], centreN: 4, treasure: 2, empty: 0.1, dens: 1.62, boss: true },
  // — کنامِ گرگ‌ها: غارهای بیضیِ نامنظم، درخت‌های زیرزمینی، پیچک و جای پنجه، آبشخور —
  46: { name: { fa: 'ردپای گرگ', en: 'Wolf Tracks' }, layout: 'scatter', cols: 136, rows: 96, rooms: 15, rw: [13, 19], rh: [10, 14],
    round: 4, shapes: ['oval', 'oval', 'L'], dress: ['claw', 'moss', 'bones'], dressN: 0.14, loops: 0.12, banners: 0, centre: ['tree'], centreN: 3, treasure: 2, empty: 0.25, dens: 1.64, startAt: 'left' },
  47: { name: { fa: 'جنگلِ زیرزمینی', en: 'Under Forest' }, layout: 'hub', cols: 144, rows: 96, rooms: 17, rw: [14, 20], rh: [11, 15],
    round: 3, shapes: ['oval'], dress: ['vine', 'moss', 'vine'], dressN: 0.18, banners: 0, centre: ['tree', 'tree', 'fire'], centreN: 6, treasure: 2, empty: 0.2, dens: 1.66 },
  48: { name: { fa: 'آبشخور', en: 'Watering Hole' }, layout: 'twin', cols: 144, rows: 96, rooms: 16, rw: [14, 20], rh: [11, 15],
    round: 4, pools: 0.75, shapes: ['oval'], dress: ['puddle', 'claw', 'moss'], dressN: 0.14, banners: 0, centre: ['tree'], centreN: 2, treasure: 2, empty: 0.2, dens: 1.68, startAt: 'left' },
  49: { name: { fa: 'غارِ زوزه', en: 'Howling Cave' }, layout: 'chain', cols: 144, rows: 96, rooms: 17, chainCols: 5, rw: [12, 17], rh: [10, 13],
    winding: true, cross: 0.3, round: 3, shapes: ['oval', 'L'], dress: ['bones', 'claw'], dressN: 0.16, banners: 0, centre: ['bones', 'fire'], centreN: 3, treasure: 3, empty: 0.15, dens: 1.69, startAt: 'top' },
  50: { name: { fa: 'کنامِ گرگِ آلفا', en: 'Alpha Den' }, layout: 'ring', cols: 144, rows: 100, rooms: 14, spokes: 3, rw: [13, 18], rh: [10, 14],
    round: 4, shapes: ['oval'], dress: ['bones', 'bones', 'claw'], dressN: 0.18, banners: 0, centre: ['tree', 'bones'], centreN: 3, treasure: 2, empty: 0.1, dens: 1.71, boss: true },
  // — تونل‌های شاخ: معدنِ سنگی، اتاق‌های L، ریل، آوارِ سنگین، چاه و سندانِ معدنچی —
  51: { name: { fa: 'تونل‌های شاخ', en: 'Horn Tunnels' }, layout: 'chain', cols: 144, rows: 96, rooms: 17, chainCols: 6, rw: [12, 16], rh: [9, 12],
    winding: true, round: 2, shapes: ['L', 'rect'], dress: ['rails', 'rubble'], dressN: 0.13, banners: 0.1, centre: ['anvil'], centreN: 2, treasure: 2, empty: 0.2, dens: 1.73, startAt: 'left' },
  52: { name: { fa: 'صخره‌های تیز', en: 'Jagged Rocks' }, layout: 'scatter', cols: 144, rows: 100, rooms: 17, rw: [13, 19], rh: [10, 14],
    cross: 0.5, round: 3, shapes: ['L', 'oval'], dress: ['rubble', 'rubble', 'claw'], dressN: 0.2, loops: 0.1, banners: 0, centre: ['crystal'], centreN: 3, treasure: 2, empty: 0.2, dens: 1.75 },
  53: { name: { fa: 'چشمه‌ی سنگی', en: 'Stone Spring' }, layout: 'hub', cols: 144, rows: 100, rooms: 17, rw: [14, 20], rh: [11, 14],
    round: 2, pools: 0.5, shapes: ['ring', 'oval'], dress: ['puddle', 'moss'], dressN: 0.14, banners: 0.2, centre: ['fountain', 'well'], centreN: 4, treasure: 2, empty: 0.2, dens: 1.77 },
  54: { name: { fa: 'گذرگاهِ کوبنده', en: 'Ramming Pass' }, layout: 'twin', cols: 152, rows: 96, rooms: 18, rw: [16, 22], rh: [9, 11],
    round: 1, shapes: ['rect', 'L'], dress: ['rails', 'rubble', 'bones'], dressN: 0.15, banners: 0.3, centre: ['cage', 'anvil'], centreN: 3, treasure: 3, empty: 0.15, dens: 1.78, startAt: 'left' },
  55: { name: { fa: 'تختِ قوچِ سنگی', en: 'Stone Ram Throne' }, layout: 'ring', cols: 152, rows: 100, rooms: 15, spokes: 4, rw: [13, 18], rh: [10, 14],
    round: 2, shapes: ['ring', 'L'], dress: ['rubble', 'rails'], dressN: 0.15, banners: 0.7, centre: ['statue', 'crystal'], centreN: 3, treasure: 2, empty: 0.1, dens: 1.80, boss: true },
  // — یخچالِ ژرف: غارهای سفید، توده‌ی برف، کریستال‌های غول، دریاچه‌ی یخ —
  56: { name: { fa: 'برف‌روب', en: 'Snowdrift' }, layout: 'scatter', cols: 144, rows: 100, rooms: 16, rw: [14, 20], rh: [11, 14],
    round: 4, shapes: ['oval', 'oval', 'L'], dress: ['snow', 'snow', 'ice'], dressN: 0.18, loops: 0.1, banners: 0, centre: ['crystal'], centreN: 3, treasure: 2, empty: 0.25, dens: 1.82, startAt: 'left' },
  57: { name: { fa: 'تالارِ یخ‌سنگ', en: 'Icestone Hall' }, layout: 'grid', cols: 152, rows: 100, gridCols: 6, gridRows: 4, holes: 0.15, rw: [13, 17], rh: [10, 13],
    round: 1, pillars: 0.5, shapes: ['rect', 'ring'], dress: ['ice', 'crystal'], dressN: 0.12, banners: 0.4, centre: ['statue', 'crystal'], centreN: 4, treasure: 3, empty: 0.15, dens: 1.84 },
  58: { name: { fa: 'دریاچه‌ی یخ', en: 'Ice Lake' }, layout: 'hub', cols: 152, rows: 100, rooms: 17, rw: [15, 21], rh: [11, 15],
    round: 4, pools: 0.85, shapes: ['oval'], dress: ['ice', 'snow'], dressN: 0.16, banners: 0, centre: ['crystal'], centreN: 2, treasure: 2, empty: 0.2, dens: 1.86 },
  59: { name: { fa: 'غارِ بهمن', en: 'Avalanche Cave' }, layout: 'chain', cols: 152, rows: 100, rooms: 18, chainCols: 5, rw: [12, 17], rh: [10, 13],
    winding: true, cross: 0.4, round: 3, shapes: ['L', 'oval'], dress: ['snow', 'rubble', 'bones'], dressN: 0.2, banners: 0, centre: ['bones', 'fire'], centreN: 3, treasure: 2, empty: 0.15, dens: 1.87, startAt: 'top' },
  60: { name: { fa: 'تختِ یتیِ کهن', en: 'Elder Yeti Throne' }, layout: 'ring', cols: 152, rows: 104, rooms: 15, spokes: 4, rw: [13, 18], rh: [10, 14],
    round: 4, shapes: ['oval', 'ring'], dress: ['snow', 'crystal', 'bones'], dressN: 0.17, banners: 0.5, centre: ['crystal', 'bones'], centreN: 4, treasure: 2, empty: 0.1, dens: 1.89, boss: true },
};
