// floors/f061_080.js — بازطراحیِ دستیِ طبقه‌های ۶۱..۸۰ (ن۱۴۴؛ جایگزینِ نسخه‌ی جدول‌محورِ ن۱۴۲).
// فصلِ ۱۳ مومیایی (مقبره‌ی غرق)، ۱۴ غول (قلبِ مذاب)، ۱۵ زامبی (گورهای بیدار)، ۱۶ عقرب (تونل‌های نیش).
export const F061_080 = {
  // — مقبره‌ی غرق: تالارهای ستون‌دار، تابوت، شن، آبِ راکد، محراب —
  61: { name: { fa: 'مقبره‌ی غرق', en: 'Drowned Tomb' }, layout: 'hub', cols: 144, rows: 100, rooms: 16, rw: [14, 19], rh: [10, 14],
    round: 1, pools: 0.5, shapes: ['rect'], dress: ['sand', 'puddle'], dressN: 0.14, banners: 0.3, centre: ['coffin'], centreN: 4, treasure: 2, empty: 0.2, dens: 1.91, startAt: 'left' },
  62: { name: { fa: 'دالانِ کتیبه', en: 'Glyph Corridor' }, layout: 'chain', cols: 152, rows: 96, rooms: 18, chainCols: 6, rw: [14, 19], rh: [9, 11],
    winding: false, round: 1, shapes: ['rect'], dress: ['candle', 'sand'], dressN: 0.12, banners: 0.8, centre: ['statue'], centreN: 4, treasure: 2, empty: 0.2, dens: 1.93, startAt: 'top' },
  63: { name: { fa: 'حوضِ مقدس', en: 'Sacred Pool' }, layout: 'ring', cols: 152, rows: 100, rooms: 16, spokes: 3, rw: [14, 20], rh: [11, 14],
    round: 2, pools: 0.6, shapes: ['ring', 'rect'], dress: ['candle', 'puddle'], dressN: 0.12, banners: 0.5, centre: ['fountain', 'altar'], centreN: 3, treasure: 2, empty: 0.2, dens: 1.95 },
  64: { name: { fa: 'خزانه‌ی فرعون', en: 'Pharaoh Vault' }, layout: 'grid', cols: 152, rows: 100, gridCols: 6, gridRows: 4, holes: 0.1, rw: [13, 17], rh: [10, 13],
    round: 1, pillars: 0.4, shapes: ['rect', 'ring'], dress: ['sand', 'bones'], dressN: 0.13, banners: 0.6, centre: ['coffin', 'statue'], centreN: 4, treasure: 5, empty: 0.15, dens: 1.96 },
  65: { name: { fa: 'تختِ مومیاییِ شاه', en: 'Mummy King Throne' }, layout: 'ring', cols: 152, rows: 104, rooms: 15, spokes: 4, rw: [13, 18], rh: [10, 14],
    round: 1, shapes: ['rect', 'ring'], dress: ['sand', 'candle'], dressN: 0.15, banners: 0.9, centre: ['coffin', 'altar'], centreN: 4, treasure: 2, empty: 0.1, dens: 1.98, boss: true },
  // — قلبِ مذاب: شکاف‌های گدازه، کوره و سندانِ غول‌ساز، کریستالِ آتشین —
  66: { name: { fa: 'قلبِ مذاب', en: 'Molten Heart' }, layout: 'scatter', cols: 144, rows: 100, rooms: 16, rw: [14, 20], rh: [10, 14],
    round: 3, shapes: ['oval', 'rect'], dress: ['crack', 'ember'], dressN: 0.16, loops: 0.1, banners: 0, centre: ['fire'], centreN: 3, treasure: 2, empty: 0.2, dens: 2.00, startAt: 'left' },
  67: { name: { fa: 'رودخانه‌ی آتش', en: 'Fire River' }, layout: 'chain', cols: 160, rows: 96, rooms: 18, chainCols: 6, rw: [13, 18], rh: [9, 12],
    winding: true, round: 2, shapes: ['oval', 'L'], dress: ['crack', 'crack', 'ember'], dressN: 0.2, banners: 0, centre: ['fire', 'bones'], centreN: 3, treasure: 2, empty: 0.15, dens: 2.02, startAt: 'top' },
  68: { name: { fa: 'کارگاهِ غول', en: 'Golem Works' }, layout: 'hub', cols: 152, rows: 104, rooms: 18, rw: [14, 20], rh: [11, 14],
    round: 1, pillars: 0.5, shapes: ['rect', 'ring'], dress: ['rubble', 'ember', 'rails'], dressN: 0.14, banners: 0.6, centre: ['anvil', 'anvil', 'statue'], centreN: 5, treasure: 3, empty: 0.15, dens: 2.04 },
  69: { name: { fa: 'دره‌ی گدازه', en: 'Lava Gorge' }, layout: 'twin', cols: 160, rows: 100, rooms: 18, rw: [16, 22], rh: [10, 13],
    cross: 0.4, round: 3, shapes: ['L', 'oval'], dress: ['crack', 'rubble'], dressN: 0.18, banners: 0, centre: ['crystal', 'fire'], centreN: 3, treasure: 2, empty: 0.15, dens: 2.05, startAt: 'left' },
  70: { name: { fa: 'تختِ غولِ سنگی', en: 'Titan Golem Throne' }, layout: 'ring', cols: 160, rows: 104, rooms: 15, spokes: 4, rw: [14, 19], rh: [10, 14],
    round: 2, shapes: ['ring', 'rect'], dress: ['crack', 'ember'], dressN: 0.17, banners: 0.8, centre: ['anvil', 'statue'], centreN: 4, treasure: 2, empty: 0.1, dens: 2.07, boss: true },
  // — گورهای بیدار: گورستانِ باتلاقی، سنگِ قبر، قفس، چاهِ طاعون، شهرِ متروک —
  71: { name: { fa: 'گورهای بیدار', en: 'Restless Graves' }, layout: 'grid', cols: 152, rows: 100, gridCols: 6, gridRows: 4, holes: 0.2, rw: [13, 17], rh: [10, 13],
    round: 2, shapes: ['rect', 'oval'], dress: ['grave', 'grave', 'moss'], dressN: 0.13, banners: 0, centre: ['coffin', 'tree'], centreN: 4, treasure: 2, empty: 0.2, dens: 2.09, startAt: 'left' },
  72: { name: { fa: 'باتلاقِ مرده', en: 'Dead Bog' }, layout: 'scatter', cols: 152, rows: 104, rooms: 17, rw: [14, 21], rh: [11, 15],
    round: 4, pools: 0.7, shapes: ['oval'], dress: ['puddle', 'moss', 'vine'], dressN: 0.18, loops: 0.12, banners: 0, centre: ['tree'], centreN: 4, treasure: 2, empty: 0.2, dens: 2.11 },
  73: { name: { fa: 'چاهِ طاعون', en: 'Plague Well' }, layout: 'hub', cols: 152, rows: 104, rooms: 17, rw: [14, 19], rh: [10, 14],
    round: 2, shapes: ['ring', 'L'], dress: ['bones', 'puddle'], dressN: 0.15, banners: 0.2, centre: ['well', 'well', 'cage'], centreN: 4, treasure: 2, empty: 0.15, dens: 2.13 },
  74: { name: { fa: 'شهرِ متروک', en: 'Forsaken Town' }, layout: 'twin', cols: 160, rows: 104, rooms: 19, rw: [13, 18], rh: [10, 13],
    round: 1, shapes: ['rect', 'L'], dress: ['rubble', 'grave', 'bones'], dressN: 0.15, banners: 0.5, centre: ['well', 'cage', 'fire'], centreN: 5, treasure: 3, empty: 0.15, dens: 2.14, startAt: 'left' },
  75: { name: { fa: 'تختِ زامبیِ سلطان', en: 'Zombie Sultan Throne' }, layout: 'ring', cols: 160, rows: 104, rooms: 15, spokes: 4, rw: [13, 18], rh: [10, 14],
    round: 3, shapes: ['oval', 'ring'], dress: ['grave', 'bones', 'candle'], dressN: 0.17, banners: 0.8, centre: ['coffin', 'bones'], centreN: 4, treasure: 2, empty: 0.1, dens: 2.16, boss: true },
  // — تونل‌های نیش: تپه‌های شن، واحه، لانه‌ی تخم، استخوانِ قربانیان —
  76: { name: { fa: 'تونل‌های نیش', en: 'Sting Tunnels' }, layout: 'chain', cols: 152, rows: 100, rooms: 18, chainCols: 6, rw: [12, 17], rh: [9, 12],
    winding: true, round: 3, shapes: ['oval', 'L'], dress: ['sand', 'bones'], dressN: 0.16, banners: 0, centre: ['bones'], centreN: 3, treasure: 2, empty: 0.2, dens: 2.18, startAt: 'left' },
  77: { name: { fa: 'تپه‌های شن', en: 'Sand Dunes' }, layout: 'scatter', cols: 160, rows: 104, rooms: 17, rw: [15, 22], rh: [11, 15],
    round: 4, shapes: ['oval', 'oval', 'L'], dress: ['sand', 'sand', 'rubble'], dressN: 0.2, loops: 0.1, banners: 0, centre: ['statue', 'bones'], centreN: 3, treasure: 2, empty: 0.25, dens: 2.20 },
  78: { name: { fa: 'واحه‌ی پنهان', en: 'Hidden Oasis' }, layout: 'hub', cols: 160, rows: 104, rooms: 18, rw: [15, 21], rh: [11, 15],
    round: 3, pools: 0.7, shapes: ['oval', 'ring'], dress: ['vine', 'sand', 'moss'], dressN: 0.16, banners: 0, centre: ['tree', 'fountain'], centreN: 5, treasure: 3, empty: 0.2, dens: 2.22 },
  79: { name: { fa: 'لانه‌ی تخم', en: 'Egg Nest' }, layout: 'twin', cols: 160, rows: 104, rooms: 19, rw: [13, 18], rh: [10, 13],
    cross: 0.4, round: 3, shapes: ['L', 'oval'], dress: ['web', 'bones', 'sand'], dressN: 0.18, banners: 0, centre: ['bones', 'cage'], centreN: 4, treasure: 2, empty: 0.15, dens: 2.23, startAt: 'left' },
  80: { name: { fa: 'تختِ عقربِ امپراتور', en: 'Emperor Scorpion Throne' }, layout: 'ring', cols: 160, rows: 108, rooms: 16, spokes: 4, rw: [14, 19], rh: [10, 14],
    round: 3, shapes: ['oval', 'ring'], dress: ['sand', 'bones'], dressN: 0.18, banners: 0.8, centre: ['statue', 'bones'], centreN: 4, treasure: 2, empty: 0.1, dens: 2.25, boss: true },
};
