// floors/f081_100.js — طراحیِ دستیِ طبقه‌های ۸۱..۱۰۰ (ن۱۴۳): فصلِ ۱۷ قارچ (جنگلِ هاگ)، ۱۸ مارمولک (معبد)، ۱۹ شوالیه‌ی سیاه (دژ)، ۲۰ اهریمن (دروازه).
// آرایش‌های ویژه: spore (هاگِ درخشان)، scale (فلس)، armor (زره و شمشیرِ افتاده)، rune (نشانِ اهریمنی). طبقه‌ی ۱۰۰ = بزرگ‌ترین نقشه + اهریمنِ اعظم.
export const F081_100 = {
  81: { centre: ['tree'], centreN: 3, name: { fa: 'لبه‌ی جنگلِ هاگ', en: 'Spore Grove Edge' }, layout: 'scatter', cols: 136, rows: 100, rooms: 16, rw: [13, 19], rh: [10, 14],
    shapes: ['oval', 'oval', 'L'], dress: ['spore', 'moss'], dressN: 0.14, loops: 0.1, treasure: 2, empty: 0.25, dens: 2.3, startAt: 'left' },
  82: { centre: ['tree', 'tree', 'well'], centreN: 3, name: { fa: 'کلاهک‌های غول', en: 'Giant Caps' }, layout: 'hub', cols: 144, rows: 100, rooms: 17, rw: [14, 20], rh: [11, 15],
    pillars: 0.6, shapes: ['ring', 'oval'], dress: ['spore', 'spore', 'vine'], dressN: 0.15, treasure: 2, empty: 0.2, dens: 2.35 },
  83: { centre: ['tree', 'fountain'], centreN: 3, name: { fa: 'تالابِ مِه', en: 'Misty Fen' }, layout: 'twin', cols: 144, rows: 100, rooms: 17, rw: [13, 19], rh: [10, 14],
    pools: 0.7, shapes: ['oval'], dress: ['puddle', 'spore', 'moss'], dressN: 0.16, treasure: 2, empty: 0.2, dens: 2.4, startAt: 'left' },
  84: { centre: ['tree', 'cage'], centreN: 3, name: { fa: 'ریشه‌گاهِ پنهان', en: 'Hidden Rootway' }, layout: 'chain', cols: 144, rows: 100, rooms: 18, chainCols: 5, rw: [12, 17], rh: [10, 13],
    winding: true, cross: 0.3, shapes: ['L', 'oval'], dress: ['vine', 'spore'], treasure: 3, empty: 0.15, dens: 2.45, startAt: 'top' },
  85: { centre: ['tree', 'altar'], centreN: 3, name: { fa: 'باغِ مادرِ قارچ‌ها', en: "Mother Mycel's Garden" }, layout: 'ring', cols: 144, rows: 100, rooms: 15, spokes: 4, rw: [13, 18], rh: [10, 14],
    round: 3, shapes: ['oval', 'ring'], dress: ['spore', 'vine'], dressN: 0.17, banners: 0.4, treasure: 2, empty: 0.1, dens: 2.5, boss: true },
  86: { centre: ['statue'], centreN: 3, name: { fa: 'پله‌های معبد', en: 'Temple Steps' }, layout: 'grid', cols: 144, rows: 100, gridCols: 6, gridRows: 4, holes: 0.15, rw: [13, 17], rh: [10, 13],
    shapes: ['rect', 'ring'], dress: ['sand', 'scale'], banners: 0.5, pillars: 0.5, treasure: 2, empty: 0.2, dens: 2.5 },
  87: { centre: ['fountain', 'altar'], centreN: 3, name: { fa: 'حوضِ قربانی', en: 'Offering Pools' }, layout: 'hub', cols: 144, rows: 100, rooms: 17, rw: [14, 20], rh: [11, 15],
    pools: 0.8, shapes: ['rect', 'oval'], dress: ['candle', 'scale', 'puddle'], dressN: 0.14, treasure: 3, empty: 0.15, dens: 2.55 },
  88: { centre: ['tree', 'statue'], centreN: 3, name: { fa: 'دالانِ پیچک‌ها', en: 'Vine Galleries' }, layout: 'chain', cols: 152, rows: 100, rooms: 18, chainCols: 6, rw: [12, 17], rh: [10, 13],
    winding: true, shapes: ['L', 'rect'], dress: ['vine', 'vine', 'scale'], dressN: 0.15, treasure: 2, empty: 0.15, dens: 2.6, startAt: 'left' },
  89: { centre: ['altar', 'altar', 'statue'], centreN: 3, name: { fa: 'محرابِ مار', en: 'Serpent Altar' }, layout: 'scatter', cols: 152, rows: 104, rooms: 18, rw: [13, 20], rh: [10, 14],
    cross: 0.4, shapes: ['ring', 'rect'], dress: ['candle', 'bones'], banners: 0.6, loops: 0.1, treasure: 2, empty: 0.15, dens: 2.65 },
  90: { centre: ['statue', 'altar'], centreN: 3, name: { fa: 'تختِ شاه‌مارمولک', en: 'Lizard King Throne' }, layout: 'ring', cols: 152, rows: 104, rooms: 15, spokes: 4, rw: [13, 18], rh: [10, 14],
    round: 3, shapes: ['rect', 'ring'], dress: ['scale', 'candle', 'sand'], dressN: 0.15, banners: 0.7, treasure: 2, empty: 0.1, dens: 2.7, boss: true },
  91: { centre: ['statue', 'anvil'], centreN: 3, name: { fa: 'دروازه‌ی دژِ سیاه', en: 'Black Citadel Gate' }, layout: 'twin', cols: 152, rows: 104, rooms: 18, rw: [13, 19], rh: [10, 14],
    shapes: ['rect'], dress: ['armor', 'rubble'], banners: 0.8, pillars: 0.4, treasure: 2, empty: 0.2, dens: 2.7, startAt: 'left' },
  92: { centre: ['bones', 'fire'], centreN: 3, name: { fa: 'میدانِ نبرد', en: 'Fallen Battlefield' }, layout: 'scatter', cols: 152, rows: 104, rooms: 18, rw: [14, 21], rh: [11, 15],
    shapes: ['oval', 'L'], dress: ['armor', 'arrows', 'bones'], dressN: 0.17, loops: 0.12, treasure: 2, empty: 0.15, dens: 2.75 },
  93: { centre: ['statue', 'statue', 'anvil'], centreN: 3, name: { fa: 'تالارِ زره‌ها', en: 'Hall of Armors' }, layout: 'grid', cols: 152, rows: 104, gridCols: 6, gridRows: 4, holes: 0.1, rw: [13, 18], rh: [10, 13],
    pillars: 0.7, shapes: ['ring', 'rect'], dress: ['armor', 'armor', 'candle'], banners: 0.7, treasure: 3, empty: 0.15, dens: 2.8 },
  94: { centre: ['cage', 'cage', 'well'], centreN: 3, name: { fa: 'سیاه‌چالِ دژ', en: 'Citadel Dungeons' }, layout: 'chain', cols: 152, rows: 104, rooms: 19, chainCols: 5, rw: [12, 16], rh: [10, 12],
    winding: true, cross: 0.4, shapes: ['L', 'rect'], dress: ['bones', 'puddle', 'armor'], dressN: 0.15, treasure: 2, empty: 0.15, dens: 2.85, startAt: 'top' },
  95: { centre: ['statue', 'coffin'], centreN: 3, name: { fa: 'تختِ شوالیه‌ی بی‌سر', en: 'Headless Knight Throne' }, layout: 'ring', cols: 152, rows: 104, rooms: 16, spokes: 4, rw: [13, 18], rh: [10, 14],
    round: 2, shapes: ['rect', 'ring'], dress: ['armor', 'candle'], dressN: 0.15, banners: 0.9, treasure: 2, empty: 0.1, dens: 2.9, boss: true },
  96: { centre: ['fire', 'altar'], centreN: 3, name: { fa: 'آستانه‌ی دوزخ', en: 'Hell Threshold' }, layout: 'twin', cols: 160, rows: 108, rooms: 19, rw: [13, 20], rh: [10, 14],
    shapes: ['oval', 'L'], dress: ['crack', 'rune', 'ember'], dressN: 0.15, treasure: 2, empty: 0.15, dens: 2.9, startAt: 'left' },
  97: { centre: ['coffin', 'bones'], centreN: 3, name: { fa: 'رودِ ارواح', en: 'River of Souls' }, layout: 'chain', cols: 160, rows: 108, rooms: 19, chainCols: 6, rw: [13, 18], rh: [10, 13],
    winding: true, pools: 0.6, shapes: ['oval', 'rect'], dress: ['rune', 'bones', 'candle'], dressN: 0.15, treasure: 2, empty: 0.15, dens: 2.95, startAt: 'top' },
  98: { centre: ['statue', 'fire', 'altar'], centreN: 3, name: { fa: 'کاخِ خاکستر', en: 'Ash Palace' }, layout: 'hub', cols: 160, rows: 108, rooms: 20, rw: [14, 21], rh: [11, 15],
    pillars: 0.6, shapes: ['ring', 'rect'], dress: ['ember', 'crack', 'rune'], banners: 0.8, treasure: 3, empty: 0.1, dens: 3 },
  99: { centre: ['bones', 'crystal'], centreN: 3, name: { fa: 'پرتگاهِ آخر', en: 'The Last Abyss' }, layout: 'scatter', cols: 160, rows: 108, rooms: 20, rw: [13, 20], rh: [10, 14],
    cross: 0.4, shapes: ['L', 'oval', 'ring'], dress: ['crack', 'crack', 'skull'], dressN: 0.17, loops: 0.12, treasure: 2, empty: 0.1, dens: 3.05 },
  100: { centre: ['altar', 'statue', 'fire'], centreN: 3, name: { fa: 'تختِ اهریمنِ اعظم', en: 'Throne of the Arch Demon' }, layout: 'ring', cols: 168, rows: 112, rooms: 16, spokes: 5, rw: [14, 20], rh: [11, 15],
    round: 3, shapes: ['oval', 'ring'], dress: ['rune', 'crack', 'candle'], dressN: 0.18, banners: 1, treasure: 3, empty: 0.05, dens: 3.2, boss: true },
};
